### ISSUE TITLE
some attwiki pages generate MWExceptions

### ISSUE THREAD

**Issue by labster** [Orain/ansible-playbook#377]
https://allthetropes.orain.org/wiki/Final_Fantasy_VII/Tear_Jerker displays:
    [f3af5e00] 2014-09-11 06:57:03: Fatal exception of type MWException

As far as I know, it's only one page having the problem.  And the content is available in edit view.

Obviously not high priority -- I'd just kinda like to know "what the fuck?".  Maybe you have a more detailed log?

**Comment by Southparkfan** [comment]
Reopening because it still occurs for the following pages (perhaps even more pages):

https://allthetropes.orain.org/wiki/The_Mighty_Boosh/FR/Ho_Yay
https://allthetropes.orain.org/wiki/Inland_Empire
https://allthetropes.orain.org/wiki/Lilo_and_Stitch_%28Disney_film%29/Heartwarming

**Comment by addshore** [comment]
2015-02-09 01:13:58 prod9.orain.org allthetropeswiki: [a5118889] /wiki/The_Mighty_Boosh/FR/Ho_Yay   Exception from line 833 of /srv/mediawiki/w/includes/db/Database.php: Database serialization may cause problems, since the connection is not restored on wakeup.
#0 /srv/mediawiki/w/includes/objectcache/RedisBagOStuff.php(332): DatabaseBase->__sleep()
#1 /srv/mediawiki/w/includes/objectcache/RedisBagOStuff.php(105): RedisBagOStuff->serialize()
#2 /srv/mediawiki/w/includes/parser/ParserCache.php(282): RedisBagOStuff->set()
#3 /srv/mediawiki/w/includes/poolcounter/PoolWorkArticleView.php(150): ParserCache->save()
#4 /srv/mediawiki/w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#5 /srv/mediawiki/w/includes/page/Article.php(688): PoolCounterWork->execute()
#6 /srv/mediawiki/w/includes/actions/ViewAction.php(44): Article->view()
#7 /srv/mediawiki/w/includes/MediaWiki.php(414): ViewAction->show()
#8 /srv/mediawiki/w/includes/MediaWiki.php(282): MediaWiki->performAction()
#9 /srv/mediawiki/w/includes/MediaWiki.php(584): MediaWiki->performRequest()
#10 /srv/mediawiki/w/includes/MediaWiki.php(435): MediaWiki->main()
#11 /srv/mediawiki/w/index.php(46): MediaWiki->run()
#12 {main}

**Comment by Southparkfan** [comment]
I'll investigate this stuff tomorrow (as soon as possible) by performing some database/redis queries and eval.php. It's a mystery to me how this happens - others are welcome to help too!

**Comment by Arcane21** [comment]
figured it out, the parser goes nuts if any images have redirect links to the basepage.

Seems to be an issue with the MWcore parser.

**Comment by Southparkfan** [comment]
Arcane21: indeed. I've discovered that these MWExceptions always are thrown when an image on a subpage (e.g. "My Title/Something/Something2") hyperlinks to its root page (in this case "My Title"). Still have no idea why.

**Comment by addshore** [comment]
> hyperlinks to its root page

?

could you provide a test example on metawiki? :)

**Comment by Southparkfan** [comment]
I tried to reproduce it on testwiki, but without any results.

**Comment by addshore** [comment]
How about exporting the exact page and all pages it depends on to testwiki and seeing?

**Comment by Southparkfan** [comment]
It might be an issue with an ATT extension, only if the issues occur on other wikis too there's a chance it's a MediaWiki bug. Exporting seems a good idea.

**Comment by addshore** [comment]
If your concerned it is an extension it is worth testing on extloadwiki where all extensions are loaded.

**Comment by Southparkfan** [comment]
"|link=Lilo_and_Stitch_(Disney_film)" and the {{work}} template are somehow related in this. If you remove the image hyperlink and keep the template, no errors are thrown, but if you keep the image hyperlink and remove the template, no errors are thrown too.

**Comment by Reception123** [comment]
@NDKilla Please close this issue as it dates from Feb 19, and it is over now.

**Comment by labster** [comment]
Eh, I'll do it.
