### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by addshore** [Orain/ansible-playbook#522]
I can not delete https://corruptionofchampions.orain.org/wiki/9_Menakjubkan_Trik_Untuk_Dapatkan_The_Most_Out_Of_Jersey_Bola_Grade_Ori_Anda

**Comment by Southparkfan** [comment]
https://corruptionofchampions.orain.org/w/index.php?title=9_Menakjubkan_Trik_Untuk_Dapatkan_The_Most_Out_Of_Jersey_Bola_Grade_Ori_Anda&action=delete works for me.

**Comment by FastLizard4** [comment]
Works for me as well.  Perhaps try logging out and logging back in again?

**Comment by TannerFilip** [comment]
I can't. SPF is a global sysadmin, not sure why FL4 can though.

**Comment by FastLizard4** [comment]
Oooh, okay.  I know what's going on.

With the new global rights organization, we (i.e., Dusti, kudu, and myself) pared down sysadmin permissions so that delete is not granted; this is therefore intentional behavior, the intention being that sysadmins should not be engaging in day-to-day steward/global sysop tasks.  Since changing this would need to be brought up on meta, I'm therefore closing this.

Note, though, that if there's an emergency or a need to do tests with delete permissions, sysadmins have the ability to change all global permissions and local groups, so delete rights can be temporarily granted as necessary.

**Comment by addshore** [comment]
... This just seems a bit stupid ... We have the technical ability to do everything, but cant do it though our nice UI...
This seems a bit insane.. but sure, guess I'll stop deleting spam and locking and blocking accounts?

**Comment by Southparkfan** [comment]
Sysadmins not having these rights is nonsense. It is their own responsibility to use them properly, but in general sysadmins should have this right to perform deletions for their "job".

**Comment by Southparkfan** [comment]
Ok, ignore "nonsense"...

**Comment by FastLizard4** [comment]
All I'm going to do is point you to [this Stewards' Noticeboard thread explaining the role restructuring][sn] and stay out of it; like I said, it wasn't really my decision, so don't shoot the messenger.  :P

[sn]: https://meta.orain.org/wiki/Stewards%27_noticeboard#Structural_changes
