### ISSUE TITLE
Need help importing a wiki dump

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#573]
Due to having to recently clean my PC due to accidentaly installing a program with lots of malware, I will need to reinstall PuTTY and retrieve my private key from a drive I backed it up on, which means I do not currently have shell acess.

The dump needing to be imported is here:

http://1drv.ms/1FSgIrO

The wiki needing the import is here:

https://meta.orain.org/wiki/Proposals_for_new_wikis#UC_Davis_Graduate_Student_Association_.28Status:_Done.29

**Comment by Southparkfan** [comment]
@Arcane21: are you sure I don't need to reset your SSH keys for security reasons because of that malware?

**Comment by Arcane21** [comment]
It was internet toolbar/search engine redirection nonsense, no rootkits or anything like that.

**Comment by Southparkfan** [comment]
Ok, I'm uploading the dump to prod8 now, and I'll let you know when the dump is imported.

**Comment by Southparkfan** [comment]
Done.

**Comment by Arcane21** [comment]
Thanks.

**Comment by Arcane21** [comment]
This needs redumped, as the old one had errors. Here's the dump and static files:

http://1drv.ms/1Hi0B48

http://1drv.ms/1Hi0B48

**Comment by labster** [comment]
I'd like to accomplish this soon, because wikispot is going down uh... today.  Or at least going into locked mode.

I also need to know to which IP I need to set up the CNAME for `gsa.ucdavis.edu`

**Comment by Southparkfan** [comment]
CNAME must be set to prod10.orain.org. I'm afraid I can't import it today, unless you can give me a direct download link - then I can quickly emtpy the wikidb and run the import in a Linux screen.

**Comment by labster** [comment]
See Arcane21's last comment.

**Comment by Southparkfan** [comment]
Will be done tomorrow as soon as I have time, promised :)

**Comment by Southparkfan** [comment]
Images (I thought you meant the XML dump was corrupted too? I couldn't find an XML dump) imported.

**Comment by labster** [comment]
Yes, the XML dump was corrupted.  Or, rather, it made a bunch of File: pages in the Main namespace.  Please delete all pages on this wiki and try again.

@Arcane21 posted the same link twice, so here's the real one: https://www.dropbox.com/s/58mxpg9fqrvldhg/ucdgsa06.7z?dl=0

**Comment by Arcane21** [comment]
oops, sorry about that.

**Comment by Southparkfan** [comment]
Some notes from importDump.php (when doing a dry run): 100 (58.76 pages/sec 498.32 revs/sec)
200 (65.96 pages/sec 602.51 revs/sec)
300 (63.26 pages/sec 837.18 revs/sec)
400 (72.82 pages/sec 740.94 revs/sec)
500 (77.85 pages/sec 649.27 revs/sec)
600 (82.41 pages/sec 586.47 revs/sec)
700 (78.96 pages/sec 492.96 revs/sec)
800 (79.22 pages/sec 442.67 revs/sec)
900 (82.91 pages/sec 421.00 revs/sec)
1000 (83.76 pages/sec 391.18 revs/sec)
Page "File:[[File(FASEB Stand Up for Science Competition.pdf)]]" was not imported because the name to which it would be imported is invalid on this wiki.
1100 (84.49 pages/sec 366.31 revs/sec)
1200 (87.30 pages/sec 354.24 revs/sec)
1300 (89.33 pages/sec 341.46 revs/sec)
1400 (90.62 pages/sec 328.12 revs/sec)
1500 (91.43 pages/sec 315.07 revs/sec)
Page "File:GSA_Weekly_Announcements_January_31_2011_2011 RESOURCE fellow info flyer[1].pdf" was not imported because the name to which it would be imported is invalid on this wiki.
Page "File:GSA_Weekly_Announcements_January_31_2011_GSA_WildernessSnowshoeing_Wtr2011_v2[1].pdf" was not imported because the name to which it would be imported is invalid on this wiki.
1600 (92.74 pages/sec 305.29 revs/sec)
1700 (93.19 pages/sec 294.21 revs/sec)
Done!
You might want to run rebuildrecentchanges.php to regenerate RecentChanges

**Comment by labster** [comment]
I'm not really concerned about those errors; there's no actual content on those pages, they're just File: stubs.  Go ahead and do the import for reals.

**Comment by Southparkfan** [comment]
Already done.

**Comment by Southparkfan** [comment]
Well actually the database is now messed up - I'll re-create the wiki.........

**Comment by Southparkfan** [comment]
Imported again - @labster @Arcane21 can you verify everything is imported correctly?

**Comment by Arcane21** [comment]
Looks fine on my end, need labster to verify.

**Comment by labster** [comment]
Looks good to me, other than the fact that I'm not an admin.

**Comment by Southparkfan** [comment]
(User rights log); 11:03 . . Southparkfan (Talk | contribs | block) changed group membership for User:Vorticity@ucdgsawiki from (none) to administrator and bureaucrat ‎(Grant founder rights (CreateWiki failed here))

**Comment by labster** [comment]
Only 5/62 files uploaded, any idea why?

**Comment by Southparkfan** [comment]
I've imported them again, now correctly?
