### ISSUE TITLE
User rights disabled with wgGroupPermissions aren't working

### ISSUE THREAD

**Issue by Wynter** [Orain/ansible-playbook#579]
I checked several wikis in wgGroupPermissions (in /roles/mediawiki/files/localsettings/LocalSettings.php.j2, about lines 1,100 to 1,400). The groups (anon and user) that should have certain user rights disabled (edit, createpage, etc.) on those wikis are not actually disabled (i.e. I can still bring up the edit page while logged out on those wikis). Wikis listed in wmgDisableAnonEditing are not affected.

**Comment by NDKilla** [comment]
I may be totally mistaken, but based on tests on a local mediawiki, setting wgGroupPermissions for any group/permission to false doesn't work. You either have to do ManualGroupOverrides (or something. I thought I saw this in the same file) or remove the permissions (if they are default) with something like unset.. Dunno. Don't work with MediaWiki much, but I believe it doesn't work.

**Comment by NDKilla** [comment]
assuming 'specificGroupOverrides' can be set for individual wikis and not 'closed' or 'private' I think this has to be used. Also, on wikis that are private but don't also have anon editing disabled, anon users can edit the main page. Is this intentional? I think '*' and 'user' should have 'edit' => false in the specificGroupOverrides. I was going to add it myself but it seemed related to this issue.

**Comment by NDKilla** [comment]
Closing this as an intentional, documented effect. Use SpecificGroupOverides (confirmed working for quantixwiki) or $wgRevokePermissions

Note that if the SpecificGroupOverrides are used, individual wikis should be defined before closed wikis so that we can still actual close wikis and enforce the changes that encompasses.

**Comment by NDKilla** [comment]
Don't know why it says SPF was unassigned twice. On a related note SPF should probably be unassigned from all issues.
